CREATE TABLE Comments (av : INT,
                mid: INT,
                lv: INT,
                fbid: VARCHAR(255),
                ad_check: INT,
                good: INT,
                isgood: INT,
                msg: TEXT,
                device: VARCHAR(255),
                [create]: INT,
                create_at: VARCHAR(255),
                reply_count: INT,
                face: VARCHAR(255),
                rank: INT,
                nick: VARCHAR(255),
                current_exp: INT,
                current_level: INT,
                current_min: INT,
                next_exp: INT,
                sex : VARCHAR(255),
                parentFeedBackId : VARCHAR(255));

CREATE TABLE Video(av : VARCHAR(255),
                   title : VARCHAR(255),
                   upName : VARCHAR(255),
                   upMid : INT,
                   createTime : VARCHAR(255),
                   zone : VARCHAR(255),
                   subZone : VARCHAR(255),
                   cid : VARCHAR(255),
                   aid : INT,
                   [view] : INT,
                   danmaku : INT,
                   reply : INT,
                   favorite : INT,
                   coin : INT,
                   share : INT,
                   now_rank : INT,
                   his_rank : INT,
                   [like] : INT,
                   no_reprINT : INT,
                   copyright : INT)

CREATE TABLE Danmu(cid : INT,
                    av : INT,
                    danmu : TEXT)